global:
  runner:
    os_image: ubuntu

tasks:
  build-deps:
    runner: razorci/openjdk
    steps:
    - checkout
    - cache/pull:
        key: maven-repo-{{ checksum "pom.xml" }}
        fallback_key: maven-repo-

    - run: mvn -q clean package
    - cache/push:
        key: maven-repo-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2 

  build-deps:
    runner: razorci/openjdk
    steps:
    - run: mvn clean test


  # deploy:
  #   stage: deploy
  #   steps:
  #     - name: Deploy Application
  #       image: alpine
  #       commands:
  #         - echo "Deploying application..."
  #         - scp -i ${SSH_PRIVATE_KEY} target/*.jar ${DEPLOY_USER}@${DEPLOY_HOST}:/path/to/deployment/directory
