global:
  runner:
    os_image: ubuntu

tasks:
  build:
    runner: razorci/openjdk:buster
    steps:
    - checkout
    - cache/pull:
        key: maven-repo-{{ checksum "JtProject/pom.xml" }}
        fallback_key: maven-repo-

    - run: cd JtProject/ && mvn -q clean package
    - cache/push:
        key: maven-repo-{{ checksum "JtProject/pom.xml" }}
        paths:
        - ~/.m2 

  test:
    runner: razorci/openjdk:buster
    steps:
    - checkout
    - run: cd JtProject/ && mvn clean test

    # - reports/junit: 
    # - target/surefire-reports/TEST-*.xml
    # - target/failsafe-reports/TEST-*.xml


  # deploy:
  #   stage: deploy
  #   steps:
  #     - name: Deploy Application
  #       image: alpine
  #       commands:
  #         - echo "Deploying application..."
  #         - scp -i ${SSH_PRIVATE_KEY} target/*.jar ${DEPLOY_USER}@${DEPLOY_HOST}:/path/to/deployment/directory
