global:
  runner:
    os_image: ubuntu

tasks:
  build:
    stage: build
    steps:
      - name: Build Project
        commands:
          - mvn clean package

  test:
    stage: test
    steps:
      - name: Run Tests
        commands:
          - mvn test

  # deploy:
  #   stage: deploy
  #   steps:
  #     - name: Deploy Application
  #       image: alpine
  #       commands:
  #         - echo "Deploying application..."
  #         - scp -i ${SSH_PRIVATE_KEY} target/*.jar ${DEPLOY_USER}@${DEPLOY_HOST}:/path/to/deployment/directory
